import { CommonModule } from '@angular/common';
import { Component, Input, ViewChild } from '@angular/core';
import {
  AbstractControl,
  FormArray,
  FormBuilder,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { patientDataTranslation, getDisplayName } from '../data/patient-schema';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { provideNativeDateAdapter } from '@angular/material/core';
import { CdkTextareaAutosize } from '@angular/cdk/text-field';

@Component({
  selector: 'app-dynamic-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonModule,
    MatDatepickerModule,
  ],
  providers: [provideNativeDateAdapter()],
  templateUrl: './dynamic-form.component.html',
  styleUrl: './dynamic-form.component.scss',
})
export class DynamicFormComponent {
  @Input() parentForm!: any; // The parent FormGroup or FormArray
  @Input() schema!: any; // The data schema for the forms
  @Input() schemaKey!: string; // The data schema key
  @Input() editMode!: boolean; // The data schema key
  @ViewChild('autosize') autosize!: CdkTextareaAutosize;

  patientDataTranslation = patientDataTranslation;

  constructor(private formBuilder: FormBuilder) {
    console.log('test');
  }

  isFormGroup(control: any): control is FormGroup {
    return control instanceof FormGroup;
  }

  isFormControl(control: any): control is FormControl {
    return control instanceof FormControl;
  }

  isFormArray(control: any): control is FormArray {
    return control instanceof FormArray;
  }

  getFormGroupControls(control: AbstractControl): any[] {
    if (this.isFormGroup(control)) {
      return Object.keys(control.controls);
    }
    return [];
  }

  getFormArrayControls(control: AbstractControl): AbstractControl[] {
    if (this.isFormArray(control)) {
      return control.controls;
    }
    return [];
  }

  getFormControl(field: string, formGroup: any): FormControl {
    const formControl = formGroup.get(field);
    return formControl;
  }

  getFormControlControls(field: string): any {
    const formControl = this.parentForm.get(field);
    return formControl.controls;
  }

  addFormGroup(formArrayName: any) {
    console.log('testing12', this.parentForm);
    const newGroup = this.createFormGroupFromSchema(
      this.schema[formArrayName].fields
    );
    // at to beginning so new groups are displayed at the top
    this.parentForm.insert(0, newGroup);
  }

  createFormGroupFromSchema(schema: any): any {
    console.log('check schema', this.schema);
    const group = this.formBuilder.group({});
    for (const field in schema) {
      // dont create field for '_id', this will be generated by mongoDB
      if (schema.hasOwnProperty(field) && field !== '_id') {
        group.addControl(
          field,
          this.formBuilder.control(
            '',
            schema[field].required ? Validators.required : null
          )
        );
      }
    }
    return group;
  }

  removeFormGroup(formArray: any, index: number) {
    console.log('testing delete', index);
    formArray.removeAt(index);
  }

  getLabel(schemaKey: string): string {
    return getDisplayName(schemaKey);
  }

  findKeyType(obj: any, key: string): string | null {
    if (obj == null || typeof obj !== 'object') {
      return null;
    }

    if (
      key in obj &&
      obj[key] &&
      typeof obj[key] === 'object' &&
      'type' in obj[key]
    ) {
      return obj[key].type;
    }

    for (const k in obj) {
      if (typeof obj[k] === 'object') {
        const result = this.findKeyType(obj[k], key);
        if (result !== null) {
          return result;
        }
      }
    }

    return null;
  }
}
